#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";


////////////////////////////////////////////////////////////////////////////////////////
// sshShell Lib
////////////////////////////////////////////////////////////////////////////////////////

[
  uuid(65A45974-A1C5-446A-921A-BE38ED553CFF),
  version(1.0),
  helpstring("ssh Shell Extension")
]
library sshShell
{

////////////////////////////////////////////////////////////////////////////////////////
// Interfaces
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
	////////////////////////////////////////////////////////////////////////////////////
	importlib("stdole2.tlb");

	////////////////////////////////////////////////////////////////////////////////////
	// ISshShell
	////////////////////////////////////////////////////////////////////////////////////
	[
	  uuid(60895968-A3DA-46FF-A72F-05243361B8E3),
      helpstring("ISshShell"),
      object,oleautomation, dual
    ]
	interface ISshShell : IDispatch
    {
		// properties
		[ 
		  id(1), 
		  helpstring("About")
		] 
		HRESULT About();
    };


////////////////////////////////////////////////////////////////////////////////////////
// Co Classes ( class factories )
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
	// sshShell
	////////////////////////////////////////////////////////////////////////////////////

	[
		uuid(6E8A9382-C824-45F4-9744-EC075876AAAB),
		aggregatable
	]
	coclass sshShell
	{
		[default]         interface     ISshShell;
	}

}