import "oaidl.idl";

////////////////////////////////////////////////////////////////////////////////////////
// mol JRE COM Lib
////////////////////////////////////////////////////////////////////////////////////////

[
  uuid(0E681FCF-0286-4e02-B95E-9A41BE384FE7),
  version(1.0),
  helpstring("JRE - COM wrapper for Java VM")
]
library JRE
{

////////////////////////////////////////////////////////////////////////////////////////
// Interfaces
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
	////////////////////////////////////////////////////////////////////////////////////
	importlib("stdole32.tlb");
	//importlib("moe.tlb");


	////////////////////////////////////////////////////////////////////////////////////
	// IJVM
	////////////////////////////////////////////////////////////////////////////////////
	[
	  uuid(5607D481-5580-4eb7-8ECD-8805846D8C86),
      helpstring("IJVM - wraps java runtime hosting"),
      object,oleautomation, dual
    ]
	interface IJVM : IDispatch
    {

		[propput,id(1), helpstring("get/set the JVM classpath")] 
		HRESULT Classpath( [in] BSTR cp );
		[propget,id(1) ] 
		HRESULT Classpath( [out,retval] BSTR* cp );

		[propput,id(2), helpstring("get/set the JVM classpath")] 
		HRESULT Libpath( [in] BSTR lp );
		[propget,id(2) ] 
		HRESULT Libpath( [out,retval] BSTR* lp );

		[id(3), helpstring("execute a Java class")] 
		HRESULT Execute([in] BSTR classfile);

		[id(4), helpstring("show a AWT/Swing form")] 
		HRESULT Show([in] BSTR classfile);

		[id(5), helpstring("init moe extension")] 
		HRESULT Extension([in] BSTR classfile, [in] IDispatch* moe, [in] IDispatch* frame);

	}

////////////////////////////////////////////////////////////////////////////////////////
// Co Classes ( class factories )
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
	// JRE
	////////////////////////////////////////////////////////////////////////////////////

	[
		uuid(B3ED4D8C-7FDD-4177-BF47-3680A8E225BC),
		helpstring("JRE - COM Object for Java VM interaction")
	]
	coclass JRE
	{
		[default]         interface     IJVM;
	}
}