import "oaidl.idl";
import "ocidl.idl";

////////////////////////////////////////////////////////////////////////////////////////
// ShellFolder Library
////////////////////////////////////////////////////////////////////////////////////////

[
  uuid(AD81C1CC-B3F3-47e8-BB69-31912616A39F),
  version(1.0),
  helpstring("ShellFolder")
]
library ShellFolder
{

////////////////////////////////////////////////////////////////////////////////////////
// Interfaces
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
	////////////////////////////////////////////////////////////////////////////////////
	importlib("stdole32.tlb");

	////////////////////////////////////////////////////////////////////////////////////
	// IShellPane
	////////////////////////////////////////////////////////////////////////////////////
	[
      uuid(8E03AB4B-E12B-42a2-905D-F106854C7153),
      helpstring("IShellPane Interface"),
      object,oleautomation, dual
    ]
	interface IShellPane : IDispatch
    {
		// properties
		[ 
		  propput,bindable,displaybind, requestedit,id(1), 
		  helpstring("Get/Set Display of files")
		] 
		HRESULT DisplayFiles([in] VARIANT_BOOL vb);

		[ 
		  propget,bindable,displaybind, requestedit,id(1)
		] 
		HRESULT DisplayFiles([out,retval] VARIANT_BOOL* vb);

		[ 
		  propput,defaultbind,bindable,displaybind, requestedit,id(2), 
		  helpstring("Get/Set current selection")
		] 
		HRESULT Selection([in] VARIANT fname);

		[ 
		  propget,defaultbind,bindable,displaybind, requestedit,id(2)
		] 
		HRESULT Selection([out,retval] VARIANT* fname);

		[ 
		  propget,id(3), 
		  helpstring("returns true when Listview has the focus")
		] 
		HRESULT HasFocus([out,retval] VARIANT_BOOL* vbHasFocus);

		// methods
		[id(4), helpstring("Update Listview")] 
		HRESULT Update();

		[id(5), helpstring("Cut current selection")] 
		HRESULT Cut();

		[id(6), helpstring("Copy current selection")] 
		HRESULT Copy();

		[id(7), helpstring("Paste current selection")] 
		HRESULT Paste();

		[id(8), helpstring("Rename current selection")] 
		HRESULT Rename();

		[id(9), helpstring("Delete current selection")] 
		HRESULT Delete();

		[id(10), helpstring("Properties for current selection")] 
		HRESULT Properties();

		[id(11), helpstring("ShellExecute current selection")] 
		HRESULT Execute();

		[id(12), helpstring("Create new directory")] 
		HRESULT CreateDir();

		[id(13), helpstring("Up to parent directory")] 
		HRESULT UpDir();

    };

////////////////////////////////////////////////////////////////////////////////////////
// Event Disp Interfaces
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
	// _IShellPaneEvents
	////////////////////////////////////////////////////////////////////////////////////

	[
	  uuid(8B2BD8F4-8788-4968-AB28-C409FF1A88CF),
	  helpstring("IShellPane Event Source Interface")
	]
	dispinterface _IShellPaneEvents
	{
		properties:
		methods:

		[id(1), helpstring("List Selection changed")]  
		void OnListSelection([in] BSTR fname);

		[id(2), helpstring("List Item DblClick")]  
		void OnListDblClick([in] BSTR fname);

		[id(3), helpstring("List Item Open")]  
		void OnListOpen([in] BSTR fname);

		[id(4), helpstring("Active Directory changed")]  
		void OnDirChanged([in] BSTR dir);
	};

////////////////////////////////////////////////////////////////////////////////////////
// Event Dual Interfaces
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
	// IShellPaneEvents
	////////////////////////////////////////////////////////////////////////////////////

    [
      uuid(3B3FF6F3-D0DB-4ada-A593-D99E6F79E6D1),
      helpstring("dual events for IShellPane"),
      object,oleautomation, dual
    ]
    interface IShellPaneEvents : IDispatch
    {
		[id(1), helpstring("List Selection changed")]  
		HRESULT OnListSelection([in] BSTR fname);

		[id(2), helpstring("List Item DblClick")]  
		HRESULT OnListDblClick([in] BSTR fname);

		[id(3), helpstring("List Item Open")]  
		HRESULT OnListOpen([in] BSTR fname);


		[id(4), helpstring("Active Directory changed")]  
		HRESULT OnDirChanged([in] BSTR dir);
	};

////////////////////////////////////////////////////////////////////////////////////////
// Co Classes ( class factories )
////////////////////////////////////////////////////////////////////////////////////////


	////////////////////////////////////////////////////////////////////////////////////
	// Directory
	////////////////////////////////////////////////////////////////////////////////////

	[
		uuid(3609D58F-1D8E-437d-BA8A-11A5DBF59BAD),
		aggregatable
	]

	coclass ShellPane
	{
		[default]         interface     IShellPane;
		[default, source] dispinterface _IShellPaneEvents;
	}

}