#ifndef DISPID_DEF_GUARD_DEFINE_SCINTILLAX_TLB_DEF_GUARD
#define DISPID_DEF_GUARD_DEFINE_SCINTILLAX_TLB_DEF_GUARD


#define DISPID_ISCINTILLAXPROPERTIES_FILENAME                                  				 1
#define DISPID_ISCINTILLAXPROPERTIES_READONLY                                  				 2
#define DISPID_ISCINTILLAXPROPERTIES_SYNTAX                                    				 3
#define DISPID_ISCINTILLAXPROPERTIES_SYSTYPE                                   				 4
#define DISPID_ISCINTILLAXPROPERTIES_ENCODING                                  				 5
#define DISPID_ISCINTILLAXPROPERTIES_TABUSAGE                                  				 6
#define DISPID_ISCINTILLAXPROPERTIES_TABINDENTS                                				 7
#define DISPID_ISCINTILLAXPROPERTIES_BACKSPACEUNINDENTS                        				 8
#define DISPID_ISCINTILLAXPROPERTIES_TABWIDTH                                  				 9
#define DISPID_ISCINTILLAXPROPERTIES_OVERTYPE                                  				 10
#define DISPID_ISCINTILLAXPROPERTIES_USECONTEXT                                				 11
#define DISPID_ISCINTILLAXPROPERTIES_WRITEBOM                                  				 12
#define DISPID_ISCINTILLAXPROPERTIES_SHOWLINENUMBERS                           				 13
#define DISPID_ISCINTILLAXPROPERTIES_SYNTAXDISPLAYNAME                         				 14
#define DISPID_ISCINTILLAXPROPERTIES_GETSYNTAXDISPLAYNAME                      				 15
#define DISPID_ISCINTILLAXPROPERTIES_SETINDENT                                 				 16
#define DISPID_ISCINTILLAXPROPERTIES_CONVERTTABS                               				 17
#define DISPID_ISCINTILLAXPROPERTIES_STYLESETS                                 				 18
#define DISPID_ISCINTILLAXSTYLESETS__NEWENUM                                   				 -4
#define DISPID_ISCINTILLAXSTYLESETS_ITEM                                       				 0
#define DISPID_ISCINTILLAXSTYLESETS_COUNT                                      				 1
#define DISPID_ISCINTILLAXSTYLESETS_JSON                                       				 2
#define DISPID_ISCINTILLAXSTYLESETS_XML                                        				 3
#define DISPID_ISCINTILLAXSTYLESET__NEWENUM                                    				 -4
#define DISPID_ISCINTILLAXSTYLESET_ITEM                                        				 0
#define DISPID_ISCINTILLAXSTYLESET_COUNT                                       				 1
#define DISPID_ISCINTILLAXSTYLESET_ID                                          				 2
#define DISPID_ISCINTILLAXSTYLESET_ADDKEYWORDS                                 				 3
#define DISPID_ISCINTILLAXSTYLESET_COUNTKEYWORDS                               				 4
#define DISPID_ISCINTILLAXSTYLESET_GETKEYWORD                                  				 5
#define DISPID_ISCINTILLAXSTYLESET_ADD                                         				 6
#define DISPID_ISCINTILLAXSTYLE_ID                                             				 1
#define DISPID_ISCINTILLAXSTYLE_DESCRIPTION                                    				 2
#define DISPID_ISCINTILLAXSTYLE_BOLD                                           				 3
#define DISPID_ISCINTILLAXSTYLE_ITALIC                                         				 4
#define DISPID_ISCINTILLAXSTYLE_EOL                                            				 5
#define DISPID_ISCINTILLAXSTYLE_FONTNAME                                       				 6
#define DISPID_ISCINTILLAXSTYLE_FONTSIZE                                       				 7
#define DISPID_ISCINTILLAXSTYLE_FORECOLOR                                      				 8
#define DISPID_ISCINTILLAXSTYLE_BACKCOLOR                                      				 9
#define DISPID_ISCINTILLAXTEXT_VALUE                                           				 0
#define DISPID_ISCINTILLAXTEXT_MODIFIED                                        				 1
#define DISPID_ISCINTILLAXTEXT_LENGTH                                          				 2
#define DISPID_ISCINTILLAXTEXT_SETTEXT                                         				 3
#define DISPID_ISCINTILLAXTEXT_GETTEXT                                         				 4
#define DISPID_ISCINTILLAXTEXT_GETTEXTRANGE                                    				 5
#define DISPID_ISCINTILLAXTEXT_APPEND                                          				 6
#define DISPID_ISCINTILLAXTEXT_INSERT                                          				 7
#define DISPID_ISCINTILLAXTEXT_SEARCH                                          				 8
#define DISPID_ISCINTILLAXTEXT_REPLACE                                         				 9
#define DISPID_ISCINTILLAXPOSITION_CARET                                       				 6
#define DISPID_ISCINTILLAXPOSITION_SEARCHPOS                                   				 1
#define DISPID_ISCINTILLAXPOSITION_ANCHOR                                      				 2
#define DISPID_ISCINTILLAXPOSITION_CHARAT                                      				 3
#define DISPID_ISCINTILLAXPOSITION_SCROLL                                      				 4
#define DISPID_ISCINTILLAXPOSITION_SCROLLINTOVIEW                              				 5
#define DISPID_ISCINTILLAXSELECTION_START                                      				 1
#define DISPID_ISCINTILLAXSELECTION_END                                        				 2
#define DISPID_ISCINTILLAXSELECTION_TEXT                                       				 3
#define DISPID_ISCINTILLAXSELECTION_GETSELECTION                               				 4
#define DISPID_ISCINTILLAXSELECTION_SETSELECTION                               				 5
#define DISPID_ISCINTILLAXSELECTION_CUT                                        				 6
#define DISPID_ISCINTILLAXSELECTION_COPY                                       				 7
#define DISPID_ISCINTILLAXSELECTION_PASTE                                      				 8
#define DISPID_ISCINTILLAXLINE_CURRENT                                         				 0
#define DISPID_ISCINTILLAXLINE_COUNT                                           				 1
#define DISPID_ISCINTILLAXLINE_LINEFROMPOS                                     				 2
#define DISPID_ISCINTILLAXLINE_POSFROMLINE                                     				 3
#define DISPID_ISCINTILLAXLINE_LINEENDPOS                                      				 4
#define DISPID_ISCINTILLAXLINE_FIRSTVISIBLELINE                                				 5
#define DISPID_ISCINTILLAXLINE_LINESONSCREEN                                   				 6
#define DISPID_ISCINTILLAXLINE_LINELENGTH                                      				 7
#define DISPID_ISCINTILLAXLINE_LINETEXT                                        				 8
#define DISPID_ISCINTILLAXLINE_SETLINETEXT                                     				 9
#define DISPID_ISCINTILLAXLINE_GOTO                                            				 10
#define DISPID_ISCINTILLAXLINE_HIGHLITE                                        				 11
#define DISPID_ISCINTILLAXANNOTATION_SETTEXT                                   				 1
#define DISPID_ISCINTILLAXANNOTATION_CLEAR                                     				 2
#define DISPID_ISCINTILLAXANNOTATION_CLEARALL                                  				 3
#define DISPID_ISCINTILLAXANNOTATION_SETSTYLE                                  				 4
#define DISPID_ISCINTILLAXMARKERS_USEMARKERS                                   				 1
#define DISPID_ISCINTILLAXMARKERS_TOGGLEMARKER                                 				 2
#define DISPID_ISCINTILLAXMARKERS_SETMARKER                                    				 3
#define DISPID_ISCINTILLAXMARKERS_REMOVE                                       				 4
#define DISPID_ISCINTILLAXMARKERS_REMOVEALL                                    				 5
#define DISPID_ISCINTILLAXMARKERS_HASMARKER                                    				 6
#define DISPID_ISCINTILLAXMARKERS_GETMARKERS                                   				 7
#define DISPID_ISCINTILLAX_PROPERTIES                                          				 1
#define DISPID_ISCINTILLAX_TEXT                                                				 2
#define DISPID_ISCINTILLAX_POSITION                                            				 3
#define DISPID_ISCINTILLAX_SELECTION                                           				 4
#define DISPID_ISCINTILLAX_LINE                                                				 5
#define DISPID_ISCINTILLAX_ANNOTATION                                          				 6
#define DISPID_ISCINTILLAX_MARKERS                                             				 7
#define DISPID_ISCINTILLAX_LOAD                                                				 8
#define DISPID_ISCINTILLAX_LOADENCODING                                        				 9
#define DISPID_ISCINTILLAX_SAVE                                                				 10
#define DISPID_ISCINTILLAX_SAVEAS                                              				 11
#define DISPID_ISCINTILLAX_UNDO                                                				 12
#define DISPID_ISCINTILLAX_REDO                                                				 13
#define DISPID_ISCINTILLAX_SAVEPOINT                                           				 14
#define DISPID_ISCINTILLAX_SETFOCUS                                            				 15
#define DISPID_ISCINTILLAX_ZOOMIN                                              				 16
#define DISPID_ISCINTILLAX_ZOOMOUT                                             				 17
#define DISPID_ISCINTILLAX_PRINT                                               				 18
#define DISPID_ISCINTILLAX_SHOWPROPERTIES                                      				 19
#define DISPID_ISCINTILLAX_INSERTCOLORDIALOG                                   				 20
#define DISPID_ISCINTILLAX_LOADASYNC                                           				 21
#define DISPID__ISCINTILLAXEVENTS_ONFILENAMECHANGED                            				 1
#define DISPID__ISCINTILLAXEVENTS_ONSHOWMENU                                   				 2
#define DISPID__ISCINTILLAXEVENTS_ONPOSCHANGE                                  				 3
#define DISPID__ISCINTILLAXEVENTS_ONCHAR                                       				 4
#define DISPID__ISCINTILLAXEVENTS_ONMARKER                                     				 5
#define DISPID__ISCINTILLAXEVENTS_ONSYNTAX                                     				 6
#define DISPID__ISCINTILLAXEVENTS_ONSYSTEM                                     				 7
#define DISPID__ISCINTILLAXEVENTS_ONENCODING                                   				 8
#define DISPID__ISCINTILLAXEVENTS_ONTABUSAGE                                   				 9
#define DISPID__ISCINTILLAXEVENTS_ONTABINDENTS                                 				 10
#define DISPID__ISCINTILLAXEVENTS_ONBACKSPACEUNINDENTS                         				 11
#define DISPID__ISCINTILLAXEVENTS_ONSHOWLINENUMBERS                            				 12
#define DISPID__ISCINTILLAXEVENTS_ONWRITEBOM                                   				 13
#define DISPID__ISCINTILLAXEVENTS_ONTABWIDTH                                   				 14
#define DISPID_ISCINTILLAXEVENTS_ONFILENAMECHANGED                             				 1
#define DISPID_ISCINTILLAXEVENTS_ONSHOWMENU                                    				 2
#define DISPID_ISCINTILLAXEVENTS_ONPOSCHANGE                                   				 3
#define DISPID_ISCINTILLAXEVENTS_ONCHAR                                        				 4
#define DISPID_ISCINTILLAXEVENTS_ONMARKER                                      				 5
#define DISPID_ISCINTILLAXEVENTS_ONSYNTAX                                      				 6
#define DISPID_ISCINTILLAXEVENTS_ONSYSTEM                                      				 7
#define DISPID_ISCINTILLAXEVENTS_ONENCODING                                    				 8
#define DISPID_ISCINTILLAXEVENTS_ONTABUSAGE                                    				 9
#define DISPID_ISCINTILLAXEVENTS_ONTABINDENTS                                  				 10
#define DISPID_ISCINTILLAXEVENTS_ONBACKSPACEUNINDENTS                          				 11
#define DISPID_ISCINTILLAXEVENTS_ONSHOWLINENUMBERS                             				 12
#define DISPID_ISCINTILLAXEVENTS_ONWRITEBOM                                    				 13
#define DISPID_ISCINTILLAXEVENTS_ONTABWIDTH                                    				 14
#endif

