#define IDD_DIALOG_COLORS               130
#define IDB_BITMAP_HSB                  130
#define IDB_BITMAP_RGB                  131
#define IDC_STATIC_RGB_RECT             1000
#define IDC_STATIC_HSB_RECT             1001
#define IDC_EDIT_RED                    1002
#define IDC_SPIN_RED                    1003
#define IDC_EDIT_GREEN                  1004
#define IDC_SPIN_GREEN                  1005
#define IDC_EDIT_BLUE                   1006
#define IDC_SPIN_BLUE                   1007
#define IDC_STATIC_OLD                  1008
#define IDC_STATIC_NEW                  1009
#define IDC_EDIT_HUE                    1010
#define IDC_SPIN_HUE                    1011
#define IDC_EDIT_SAT                    1012
#define IDC_SPIN_SAT                    1013
#define IDC_EDIT_VAL                    1014
#define IDC_SPIN_VAL                    1015
#define IDC_EDIT_HEX                    1016
#define IDC_BUTTON_PICK                 1017
