#ifndef DISPID_DEF_GUARD_DEFINE_SHELLCTRL_TLB_DEF_GUARD
#define DISPID_DEF_GUARD_DEFINE_SHELLCTRL_TLB_DEF_GUARD


#define DISPID_ISHELLTREE_DISPLAYFILES                                         				 1
#define DISPID_ISHELLTREE_SELECTION                                            				 2
#define DISPID_ISHELLTREE_HASFOCUS                                             				 3
#define DISPID_ISHELLTREE_UPDATE                                               				 4
#define DISPID_ISHELLTREE_CUT                                                  				 5
#define DISPID_ISHELLTREE_COPY                                                 				 6
#define DISPID_ISHELLTREE_PASTE                                                				 7
#define DISPID_ISHELLTREE_RENAME                                               				 8
#define DISPID_ISHELLTREE_DELETE                                               				 9
#define DISPID_ISHELLTREE_PROPERTIES                                           				 10
#define DISPID_ISHELLTREE_EXECUTE                                              				 11
#define DISPID_ISHELLTREE_ADDFOLDER                                            				 12
#define DISPID_ISHELLTREE_REMOVEFOLDER                                         				 13
#define DISPID_ISHELLTREE_CREATEDIR                                            				 14
#define DISPID_ISHELLTREE_USECONTEXT                                           				 15
#define DISPID_ISHELLTREE_ISDIR                                                				 16
#define DISPID_IHEXCTRL_READONLY                                               				 1
#define DISPID_IHEXCTRL_DISPLAYCOLUMNS                                         				 2
#define DISPID_IHEXCTRL_FILENAME                                               				 3
#define DISPID_IHEXCTRL_HASFOCUS                                               				 4
#define DISPID_IHEXCTRL_SHOWTOOLBAR                                            				 5
#define DISPID_IHEXCTRL_SCROLLPOS                                              				 6
#define DISPID_IHEXCTRL_SCROLLMAX                                              				 7
#define DISPID_IHEXCTRL_OFFSET                                                 				 8
#define DISPID_IHEXCTRL_FILESIZE                                               				 9
#define DISPID_IHEXCTRL_SEARCHPOS                                              				 10
#define DISPID_IHEXCTRL_OPEN                                                   				 11
#define DISPID_IHEXCTRL_OPENREADONLY                                           				 12
#define DISPID_IHEXCTRL_SETOFFSETDWORD                                         				 13
#define DISPID_IHEXCTRL_SETOFFSETBYTE                                          				 14
#define DISPID_IHEXCTRL_SETOFFSETCHAR                                          				 15
#define DISPID_IHEXCTRL_SEARCH                                                 				 16
#define DISPID_IHEXCTRL_VALUE                                                  				 17
#define DISPID_ISHELLLIST_DISPLAYFILES                                         				 1
#define DISPID_ISHELLLIST_SELECTION                                            				 2
#define DISPID_ISHELLLIST_HASFOCUS                                             				 3
#define DISPID_ISHELLLIST_UPDATE                                               				 4
#define DISPID_ISHELLLIST_CUT                                                  				 5
#define DISPID_ISHELLLIST_COPY                                                 				 6
#define DISPID_ISHELLLIST_PASTE                                                				 7
#define DISPID_ISHELLLIST_RENAME                                               				 8
#define DISPID_ISHELLLIST_DELETE                                               				 9
#define DISPID_ISHELLLIST_PROPERTIES                                           				 10
#define DISPID_ISHELLLIST_EXECUTE                                              				 11
#define DISPID_ISHELLLIST_CREATEDIR                                            				 12
#define DISPID_ISHELLLIST_UPDIR                                                				 13
#define DISPID_ISCPLIST_LOCATION                                               				 1
#define DISPID_ISCPLIST_HASFOCUS                                               				 2
#define DISPID_ISCPLIST_SELECTION                                              				 3
#define DISPID_ISCPLIST_UPDATE                                                 				 4
#define DISPID_ISCPLIST_CUT                                                    				 5
#define DISPID_ISCPLIST_COPY                                                   				 6
#define DISPID_ISCPLIST_PASTE                                                  				 7
#define DISPID_ISCPLIST_RENAME                                                 				 8
#define DISPID_ISCPLIST_DELETE                                                 				 9
#define DISPID_ISCPLIST_PROPERTIES                                             				 10
#define DISPID_ISCPLIST_CREATEDIR                                              				 11
#define DISPID_ISCPLIST_UPDIR                                                  				 12
#define DISPID_ISCPLIST_COPYTO                                                 				 13
#define DISPID_ISCPLIST_EXECUTE                                                				 14
#define DISPID_ICOLORPICKER_COLOR                                              				 1
#define DISPID_ICOLORPICKER_HEXCOLOR                                           				 2
#define DISPID_ICOLORPICKER_SHOW                                               				 3
#define DISPID_IPID_PID                                                        				 0
#define DISPID_IPID_NAME                                                       				 1
#define DISPID_IPID_TERMINATEPROCESS                                           				 2
#define DISPID_IKILLROY_FINDPIDFORFILE                                         				 1
#define DISPID__ISHELLTREEEVENTS_ONTREESELECTION                               				 1
#define DISPID__ISHELLTREEEVENTS_ONTREEDBLCLICK                                				 2
#define DISPID__ISHELLTREEEVENTS_ONTREEOPEN                                    				 3
#define DISPID__ISHELLTREEEVENTS_ONCONTEXTMENU                                 				 4
#define DISPID__IHEXCTRLEVENTS_ONNEWFILE                                       				 1
#define DISPID__IHEXCTRLEVENTS_ONNEWOFFSET                                     				 2
#define DISPID__IHEXCTRLEVENTS_ONNEWVALUE                                      				 3
#define DISPID__ISHELLLISTEVENTS_ONLISTSELECTION                               				 1
#define DISPID__ISHELLLISTEVENTS_ONLISTDBLCLICK                                				 2
#define DISPID__ISHELLLISTEVENTS_ONLISTOPEN                                    				 3
#define DISPID__ISHELLLISTEVENTS_ONDIRCHANGED                                  				 4
#define DISPID_ISHELLTREEEVENTS_ONTREESELECTION                                				 1
#define DISPID_ISHELLTREEEVENTS_ONTREEDBLCLICK                                 				 2
#define DISPID_ISHELLTREEEVENTS_ONTREEOPEN                                     				 3
#define DISPID_ISHELLTREEEVENTS_ONCONTEXTMENU                                  				 4
#define DISPID_ISHELLLISTEVENTS_ONLISTSELECTION                                				 1
#define DISPID_ISHELLLISTEVENTS_ONLISTDBLCLICK                                 				 2
#define DISPID_ISHELLLISTEVENTS_ONLISTOPEN                                     				 3
#define DISPID_ISHELLLISTEVENTS_ONDIRCHANGED                                   				 4
#define DISPID_IHEXCTRLEVENTS_ONNEWFILE                                        				 1
#define DISPID_IHEXCTRLEVENTS_ONNEWOFFSET                                      				 2
#define DISPID_IHEXCTRLEVENTS_ONNEWVALUE                                       				 3
#endif

