#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";


////////////////////////////////////////////////////////////////////////////////////////
// moeShell Lib
////////////////////////////////////////////////////////////////////////////////////////

[
  uuid(19D819D7-5191-4dfc-8FD5-654908D97BD1),
  version(1.0),
  helpstring("Moe Shell Extension")
]
library moeShell
{

////////////////////////////////////////////////////////////////////////////////////////
// Interfaces
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
	////////////////////////////////////////////////////////////////////////////////////
	importlib("stdole2.tlb");

	////////////////////////////////////////////////////////////////////////////////////
	// ISetting
	////////////////////////////////////////////////////////////////////////////////////
	[
	  uuid(B5DE89C4-B9AC-4d5a-A2EA-C472D536D36B),
      helpstring("ImoeShell"),
      object,oleautomation, dual
    ]
	interface ImoeShell : IDispatch
    {
		// properties
		[ 
		  id(1), 
		  helpstring("About")
		] 
		HRESULT About();
    };


////////////////////////////////////////////////////////////////////////////////////////
// Co Classes ( class factories )
////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////////
	// moeShell
	////////////////////////////////////////////////////////////////////////////////////

	[
		uuid(AF110465-5902-4db8-8DF3-FBA079547D08),
		aggregatable
	]
	coclass moeShell
	{
		[default]         interface     ImoeShell;
	}

}