/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_oha7_dispdriver_impl_Native */

#ifndef _Included_org_oha7_dispdriver_impl_Native
#define _Included_org_oha7_dispdriver_impl_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef org_oha7_dispdriver_impl_Native_DISPATCH_METHOD
#define org_oha7_dispdriver_impl_Native_DISPATCH_METHOD 1L
#undef org_oha7_dispdriver_impl_Native_DISPATCH_PROPERTYGET
#define org_oha7_dispdriver_impl_Native_DISPATCH_PROPERTYGET 2L
#undef org_oha7_dispdriver_impl_Native_DISPATCH_PROPERTYPUT
#define org_oha7_dispdriver_impl_Native_DISPATCH_PROPERTYPUT 4L
#undef org_oha7_dispdriver_impl_Native_DISPATCH_PROPERTYPUTREF
#define org_oha7_dispdriver_impl_Native_DISPATCH_PROPERTYPUTREF 8L
/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    QueryInterface
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_oha7_dispdriver_impl_Native_QueryInterface
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    Addref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_oha7_dispdriver_impl_Native_Addref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_oha7_dispdriver_impl_Native_Release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    CoIninitalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_oha7_dispdriver_impl_Native_CoIninitalize
  (JNIEnv *, jclass);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    CoUnIninitalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_oha7_dispdriver_impl_Native_CoUnIninitalize
  (JNIEnv *, jclass);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    CreateObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_oha7_dispdriver_impl_Native_CreateObject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    RetrieveBstr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_oha7_dispdriver_impl_Native_RetrieveBstr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    Invoke
 * Signature: (JI[Ljava/lang/Class;[Ljava/lang/Object;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_oha7_dispdriver_impl_Native_Invoke
  (JNIEnv *, jclass, jlong, jint, jobjectArray, jobjectArray, jint);

/*
 * Class:     org_oha7_dispdriver_impl_Native
 * Method:    GetObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_oha7_dispdriver_impl_Native_GetObject
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
